name: mochi
description: Mochi messenger
publish_to: none

version: 0.4.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  timeago: ^2.0.29
  cupertino_icons: ^0.1.2
  faker: ^1.2.1
  base58check: ^1.0.1
  equatable: ^1.2.5
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  uuid: ^2.2.2
  flutter_local_notifications: ^4.0.0
  device_info: ^0.4.2+4
  http: ^0.12.0+4
  path_provider: ^1.6.7
  rxdart: ^0.24.0
  shared_preferences: ^0.5.7
  google_fonts: ^1.1.2
  nimona:
    path: ../flutter-nimona

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
