name: mochi
description: Mochi messenger
publish_to: none

version: 0.6.4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  nimona:
    path: ../flutter-nimona
  base58check: ^1.0.1
  bloc: ^6.1.1
  cupertino_icons: ^0.1.2
  device_info: ^0.4.2+4
  equatable: ^1.2.5
  faker: ^1.2.1
  flutter_bloc: ^6.1.1
  flutter_local_notifications: ^4.0.0
  google_fonts: ^1.1.2
  http: ^0.12.0+4
  intl: ^0.17.0-nullsafety.2
  path_provider: ^1.6.27
  rxdart: ^0.24.0
  shared_preferences: ^0.5.7
  time_formatter: ^1.0.0+5
  timeago: ^2.0.29
  uuid: ^2.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/en.json
