// Objective-C API for talking to mochi.io/mobile Go package.
//   gobind -lang=objc mochi.io/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Gomobile_H__
#define __Gomobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class GomobileDataProcessor;

/**
 * DataProcessor :
 */
@interface GomobileDataProcessor : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Increment : Increment the int received as an argument.
 */
- (BOOL)increment:(long)data ret0_:(long* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
@end

#endif
